# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'pg'
require 'simplecov'
require 'fabrication'
require 'rspec'
require 'sequel'
require 'database_cleaner'
require 'pry'
require 'database_cleaner'
require 'aruba/api'

ENV['NETATLAS_ENV'] = 'test'
SimpleCov.start if File.basename($0) == 'rspec'

DB = Sequel.connect('postgres://postgres@localhost/netatlas_test')
require 'netatlas/client'
require 'netatlas/factories'
Dir["./spec/support/**/*.rb"].map {|f| require File.expand_path(f)}

NetAtlas.setup(:url => 'http://test.netatlas.lvh.me', :user => 'admin@netatlas.com', :password => 'password')
require_relative "../lib/netatlas/resource"
Dir[File.dirname(__FILE__) + "/../lib/netatlas/resource/*.rb"].each {|file| require file }

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.include Aruba::Api, :example_group => {
    :file_path => /spec\/cli/
  }
  config.before(:suite) do
    DatabaseCleaner.strategy = :truncation
  end

  config.before(:each) do 
    DatabaseCleaner.clean
  end

  config.after(:each) do
  end
end
ENV['PATH'] = "#{File.expand_path(File.dirname(__FILE__) + '/bin')}#{File::PATH_SEPARATOR}#{ENV['PATH']}"
